name: Build On Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        ls
        sudo chmod +x build.sh
        ./build.sh
