name: Continuous Integration


on: [push]

jobs:
  build:
    name: Linux Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      run: |
        mkdir bin
        make    
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-binaries
        path: bin
